version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Host port 8080 maps to container port 80
    depends_on:
      - user-service
      - order-service
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf  # Mount renamed config file

  user-service:
    build: ./user-service
    # ports:
    #   - "5001:5001"  # Removed to prevent direct host access

  order-service:
    build: ./order-service
    # ports:
    #   - "5002:5002"  # Removed to prevent direct host access
